making CI better

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -9,17 +9,42 @@ on:
     branches: [ "dev" ]
 
 jobs:
-  build:
+  build-and-test:
     runs-on: windows-latest
 
     steps:
     - uses: actions/checkout@v4
 
     - name: Configure CMake
-      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -S ${{ github.workspace }} -B ${{ github.workspace }}/build  -DBUILD_OTHER_TESTS=ON
+      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -S ${{ github.workspace }} -B ${{ github.workspace }}/build  -DBUILD_OTHER_TESTS=ON -DBUILD_DEVELOPMENT_DRIVERS=OFF
 
     - name: Build
       run: python ${{ github.workspace }}/cli.py -b -c=Release
 
     - name: Run Tests
       run: python ${{ github.workspace }}/cli.py -t -c=Release
+      continue-on-error: true
+      
+    - name: Check Test Results
+      run: |
+        if [ -f ${{ github.workspace }}/build/other_test_results.xml ]; then
+          echo "Test results found."
+        else
+          echo "Test results not found!"
+          exit 1
+        fi
+        ## check if tests passed
+        if grep -q 'failures="0"' ${{ github.workspace }}/build/other_test_results.xml; then
+          echo "All tests passed."
+        else
+          echo "Some tests failed!"
+          exit 1
+        fi
+      continue-on-error: true
+
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v3
+      if: always()
+      with:
+        name: other-test-results
+        path: ${{ github.workspace }}/build/other_test_results.xml
